name: Build SpaServer

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/spa-server

jobs:
  linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Build '${{ env.IMAGE_NAME }}'
        run: |
          docker build \
              --file src/Spa.Server/Dockerfile \
              --tag ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }} \
              .

      - name: Login to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push '${{ env.IMAGE_NAME }}'
        if: github.event_name != 'pull_request'
        run: docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
